language: android
sudo: required
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
  - sys-img-x86-google_apis-26
  - sys-img-armeabi-v7a-android-22
env:
  global:
  - ANDROID_API=26
  - EMULATOR_API=22
  - ANDROID_BUILD_TOOLS=26.0.2
  - ADB_INSTALL_TIMEOUT=5
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_script:
- android list targets
- android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1="";
  print $2}'
- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
deploy:
  provider: releases
  api_key:
    secure: V35/bNAxahticsmJ30c4W1wHmUHs0dbPhd8qbhkbLE79MeV0qtJ3LLsRKWU8SinKTB0DYcWdc4Hq2ha2i0rHHNAWP38JdwBGTsKRxEcXPQt+lKobsoopg0N4OqpMO6ltlGphHIu9xQRd7IAdxP04At+gIzXh8GC7uml9PNJWptUk0FNPk3k1SwJoMWowwqEcK8DnvgbCTNwEDwF6ieoX2XUyFTd0aIJ5ry0D1BAYLSyDnH4xR1kwFOBRDLhbzCYLqfuBKCrXXSur/ZJk0ZTyI37KP2nDVuH27O91Dik+nepR0UcTUqC/2KneOaP9kfWkXBxeHyKXgo0jaxZ94Fiw1m0aoJIpvh1GnC2J0UgAQ9Jq7n74sBAJbXEhdSya/u6ezP7wV4adgimMUO4pdjh7Pft820Y37ul70PNQ024qA3euyFQ1Btkmq07SwE5qriB5M6CBM8ji7r5U9PVyGwD4mEz92oWcQb673hEqlwh0x97uKWgkFv+fVUFD58W+kVM9myi9pUo++hZ8ApaslMaUzHwHh9gnOvNec4xqtw8BC8kZBz5/1T/BFk525JKaH/l0Rg7u/ibWEScUQy6wgNPC1c7D1Tg8zp9gR61dz207hwQo0uMYebhbvVb5+y5R46mvvGFT42zx+wkbTjGsdHitCH12h5Pyv6r7OXgvEpAI55s=
  file: app/build/outputs/apk/yourapp*release*.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: shreejadhav10/GitAdroidStudioDemo1
after_success:
- sh set_tags.sh
